name:                graphWikip
version:             0.1.0.0
github:              "githubuser/graphWikip"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/graphWikip#readme>

default-extensions:
  - FlexibleContexts
  - LambdaCase
  - OverloadedStrings
  - StrictData
  - TypeApplications
  - TupleSections
  - BangPatterns
  - NamedFieldPuns
  - RecordWildCards

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - vector
  - safe-exceptions
  - mtl
  - hedis
  - containers
  - unordered-containers

library:
  source-dirs: src

executables:
  graphWikip-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -O2
    dependencies:
      - filepath
      - directory
      - graphviz
      - graphWikip

tests:
  graphWikip-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphWikip
